services:
  vector-db:
    image: qdrant/qdrant:latest
    container_name: docochat-qdrant
    volumes:
      - docochat_volume:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
  app:
    build: .
    container_name: docochat-app
    depends_on:
      - vector-db
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - QDRANT_REST_API=http://vector-db:6333
volumes:
  docochat_volume: